using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Filtering.Net.Generator;

/// <summary>
/// Resolves filter profiles either by mapping a CLR property type to a built-in profile
/// (<c>StringFilter</c>, <c>NumberFilter</c>, etc.) or by reading the operator list off an
/// explicit user-specified profile type.
/// </summary>
internal static class ProfileResolver
{
    public const string StringFilterFullName = "Filtering.Net.StringFilter";
    public const string DateTimeFilterFullName = "Filtering.Net.DateTimeFilter";
    public const string DateTimeOffsetFilterFullName = "Filtering.Net.DateTimeOffsetFilter";
    public const string DateOnlyFilterFullName = "Filtering.Net.DateOnlyFilter";
    public const string TimeOnlyFilterFullName = "Filtering.Net.TimeOnlyFilter";
    public const string BoolFilterFullName = "Filtering.Net.BoolFilter";
    public const string GuidFilterFullName = "Filtering.Net.GuidFilter";
    public const string Int32FilterFullName = "Filtering.Net.Int32Filter";
    public const string Int64FilterFullName = "Filtering.Net.Int64Filter";
    public const string Int16FilterFullName = "Filtering.Net.Int16Filter";
    public const string ByteFilterFullName = "Filtering.Net.ByteFilter";
    public const string DecimalFilterFullName = "Filtering.Net.DecimalFilter";
    public const string DoubleFilterFullName = "Filtering.Net.DoubleFilter";
    public const string SingleFilterFullName = "Filtering.Net.SingleFilter";

    private const string FilterOperatorAttributeFullName = "Filtering.Net.FilterOperatorAttribute";
    private const string FilterProfileAttributeFullName = "Filtering.Net.FilterProfileAttribute<T>";

    private static readonly IReadOnlyList<CustomOperatorModel> EmptyCustomOperators = [];

    /// <summary>Open-generic display string used to recognise an auto-emitted enum profile
    /// (one of the <c>Filtering.Net.Generated.*Filter</c> classes produced by
    /// <c>EnumProfileEmitter</c>).</summary>
    private const string AutoEmittedEnumProfileNamespace = "Filtering.Net.Generated";

    /// <summary>Builds a synthetic <see cref="ResolvedProfile"/> for an auto-emitted enum
    /// profile that the source compilation can't yet see (the profile is generated by the
    /// same pass that's calling us). Returns null when <paramref name="profileFullName"/>
    /// doesn't fit the auto-emitted enum profile naming pattern or the property isn't an
    /// enum — the caller will then fall back to <see cref="InferFromClrType"/>.</summary>
    public static ResolvedProfile? TryBuildVirtualEnumProfile(string profileFullName, ITypeSymbol propertyType)
    {
        if (!profileFullName.StartsWith(AutoEmittedEnumProfileNamespace + ".", StringComparison.Ordinal))
        {
            return null;
        }
        var unwrapped = UnwrapNullable(propertyType);
        if (unwrapped.TypeKind != TypeKind.Enum)
        {
            return null;
        }
        return new ResolvedProfile(profileFullName, BuiltInEnumOperators, EmptyCustomOperators);
    }

    /// <summary>True for an auto-emitted enum profile (a class under
    /// <c>Filtering.Net.Generated</c> produced by <c>EnumProfileEmitter</c>). These profiles
    /// own their own <c>TryGetValue</c>/<c>TryGetArray</c> helpers, so the emitter can call
    /// them directly without walking <c>BasedOn</c>.</summary>
    public static bool IsAutoEmittedEnumProfile(string profileFullName) =>
        profileFullName.StartsWith(AutoEmittedEnumProfileNamespace + ".", StringComparison.Ordinal);

    /// <summary>True when <paramref name="profileFullName"/> identifies a profile that ships
    /// its own <c>TryGetValue</c>/<c>TryGetArray</c> extractor — either a built-in (a
    /// <c>Filtering.Net.*Filter</c> class) or an auto-emitted per-enum profile. Custom
    /// user-defined profiles do not own extractors; they need the emitter to walk to the
    /// <c>BasedOn</c> root.</summary>
    public static bool ProfileOwnsExtractor(string profileFullName) =>
        IsBuiltInProfileName(profileFullName) || IsAutoEmittedEnumProfile(profileFullName);

    /// <summary>Walks the <see cref="FilterProfileAttribute{T}.BasedOn"/> chain on
    /// <paramref name="profileType"/> to find the first ancestor profile that owns its own
    /// extractor (a built-in or, in principle, an auto-emitted enum profile — auto-emitted
    /// profiles never appear in a user's <c>BasedOn</c> chain in practice). Returns the input
    /// profile's full name when it itself owns an extractor, or when no extractor-owning base
    /// could be found (the latter is a defensive fallback; FN0008 / consumer compile errors
    /// surface the misconfiguration).</summary>
    public static string ResolveExtractorProfileFullName(INamedTypeSymbol profileType)
    {
        var visited = new HashSet<string>(StringComparer.Ordinal);
        var current = profileType;
        while (current is not null)
        {
            var fullName = current.ToDisplayString();
            if (!visited.Add(fullName)) break; // cycle guard
            if (ProfileOwnsExtractor(fullName)) return fullName;

            INamedTypeSymbol? next = null;
            foreach (var attributeData in current.GetAttributes())
            {
                if (attributeData.AttributeClass?.OriginalDefinition?.ToDisplayString() != FilterProfileAttributeFullName) continue;
                foreach (var namedArgument in attributeData.NamedArguments)
                {
                    if (namedArgument.Key != "BasedOn") continue;
                    if (namedArgument.Value.Value is INamedTypeSymbol basedOnType)
                    {
                        next = basedOnType;
                    }
                }
            }
            if (next is null) break;
            current = next;
        }
        return profileType.ToDisplayString();
    }

    /// <summary>
    /// Reads the operator list from an explicitly specified profile type. Walks the
    /// <c>[FilterProfile(BasedOn = typeof(...))]</c> chain so a derived profile inherits its
    /// base profile's operators, with the derived profile's <c>[FilterOperator]</c>-marked
    /// members overriding any same-named operator from the base.
    /// </summary>
    /// <remarks>
    /// Cycle protection: a profile referencing itself (directly or indirectly) via
    /// <c>BasedOn</c> would otherwise loop forever. The traversal short-circuits when it
    /// re-encounters a profile already on the resolution stack.
    /// </remarks>
    public static ResolvedProfile? ResolveExplicit(INamedTypeSymbol profileType, Compilation? compilation = null)
    {
        var visited = new HashSet<string>(StringComparer.Ordinal);
        // Operator name -> declaring profile full name; derived-profile overwrites win.
        var operatorDeclarers = new Dictionary<string, string>(StringComparer.Ordinal);
        // Operator name -> custom-operator metadata (only present when the declaring member
        // is on a non-built-in profile and the lambda body could be extracted).
        var operatorMetadata = new Dictionary<string, CustomOperatorModel>(StringComparer.Ordinal);
        // Insertion order preserves the user's declaration order in the snapshot output.
        var operatorOrder = new List<string>();

        CollectOperatorsRecursive(profileType, compilation, visited, operatorDeclarers, operatorMetadata, operatorOrder);

        var profileFullName = profileType.ToDisplayString();
        var customOperators = operatorOrder
            .Where(name => operatorMetadata.ContainsKey(name))
            .Select(name => operatorMetadata[name])
            .ToList();
        return new ResolvedProfile(profileFullName, operatorOrder, customOperators);
    }

    /// <summary>Walks <c>BasedOn</c> base-first, then the current profile, so derived
    /// operators overwrite same-named base operators (and overwrite their custom-operator
    /// metadata if both halves declare the same operator).</summary>
    private static void CollectOperatorsRecursive(
        INamedTypeSymbol profileType,
        Compilation? compilation,
        HashSet<string> visited,
        Dictionary<string, string> operatorDeclarers,
        Dictionary<string, CustomOperatorModel> operatorMetadata,
        List<string> operatorOrder)
    {
        var profileFullName = profileType.ToDisplayString();
        if (!visited.Add(profileFullName)) return; // cycle guard

        var isBuiltIn = IsBuiltInProfileName(profileFullName);

        // Recurse into BasedOn first so the derived profile's same-named operator wins.
        foreach (var attributeData in profileType.GetAttributes())
        {
            if (attributeData.AttributeClass?.OriginalDefinition?.ToDisplayString() != FilterProfileAttributeFullName) continue;
            foreach (var namedArgument in attributeData.NamedArguments)
            {
                if (namedArgument.Key != "BasedOn") continue;
                if (namedArgument.Value.Value is not INamedTypeSymbol basedOnType) continue;
                CollectOperatorsRecursive(basedOnType, compilation, visited, operatorDeclarers, operatorMetadata, operatorOrder);
            }
        }

        foreach (var member in profileType.GetMembers())
        {
            // [FilterOperator] is allowed on properties and methods.
            if (member is not IPropertySymbol && member is not IMethodSymbol) continue;
            foreach (var attributeData in member.GetAttributes())
            {
                if (attributeData.AttributeClass?.ToDisplayString() != FilterOperatorAttributeFullName) continue;
                if (attributeData.ConstructorArguments.Length == 0) continue;
                if (attributeData.ConstructorArguments[0].Value is not string operatorName) continue;

                if (!operatorDeclarers.ContainsKey(operatorName))
                {
                    operatorOrder.Add(operatorName);
                }
                operatorDeclarers[operatorName] = profileFullName;

                if (isBuiltIn)
                {
                    // Built-in profile operators are emitted via BuiltInProfileCatalog; no
                    // metadata required (and we can drop any inherited custom metadata for
                    // the same name when a derived custom profile re-declared it earlier
                    // in the recursion — that scenario can't happen because we walk base
                    // first, but the explicit Remove keeps the invariant clear).
                    operatorMetadata.Remove(operatorName);
                    continue;
                }

                var customMetadata = TryBuildCustomOperatorModel(member, operatorName, profileFullName, compilation);
                if (customMetadata is not null)
                {
                    operatorMetadata[operatorName] = customMetadata;
                }
                else
                {
                    operatorMetadata.Remove(operatorName);
                }
            }
        }
    }

    /// <summary>True for any profile shipped from <c>Filtering.Net</c> — recognised by
    /// namespace prefix. Mirrors <see cref="BuiltInProfileCatalog.IsBuiltIn"/> but lives here
    /// to keep the resolver independent of the emission layer.</summary>
    private static bool IsBuiltInProfileName(string profileFullName) =>
        profileFullName.StartsWith("Filtering.Net.", StringComparison.Ordinal)
        && !profileFullName.StartsWith("Filtering.Net.Generated.", StringComparison.Ordinal);

    /// <summary>
    /// Best-effort extractor for a custom-operator's lambda metadata. Returns null when
    /// the member's syntax doesn't look like the documented
    /// <c>=&gt; (column, value) =&gt; expression</c> shape (or its unary variant); the
    /// emitter then falls back to a throwing stub for that operator.
    /// </summary>
    /// <remarks>
    /// Supported member shapes:
    /// <list type="bullet">
    /// <item>Expression-bodied property: <c>public static Expression&lt;Func&lt;T, U, bool&gt;&gt; Op =&gt; (a, b) =&gt; …;</c></item>
    /// <item>Block-bodied property getter that returns a parenthesized lambda directly.</item>
    /// <item>Expression-bodied method: <c>public static Expression&lt;Func&lt;T, U, bool&gt;&gt; Op() =&gt; (a, b) =&gt; …;</c></item>
    /// </list>
    /// Other shapes (statement-bodied methods, lambdas constructed via Expression.Lambda
    /// factory APIs, etc.) yield null. The corresponding leaf method then falls back to
    /// the generator's throwing stub.
    /// </remarks>
    private static CustomOperatorModel? TryBuildCustomOperatorModel(
        ISymbol operatorMember,
        string operatorName,
        string declaringProfileFullName,
        Compilation? compilation)
    {
        var lambdaSyntax = TryFindLambdaSyntax(operatorMember);
        if (lambdaSyntax is null) return null;

        var parameters = lambdaSyntax.ParameterList.Parameters;
        if (parameters.Count == 0 || parameters.Count > 2) return null;

        var columnParameterName = parameters[0].Identifier.Text;
        string? valueParameterName = null;
        string? valueClrType = null;
        var isArrayValue = false;

        if (parameters.Count == 2)
        {
            valueParameterName = parameters[1].Identifier.Text;
            // Pull the value type from the symbol's type signature: the property/method's
            // type is Expression<Func<TColumn, TValue, bool>>; TypeArguments[0] is the
            // Func, whose TypeArguments[1] is TValue.
            var valueType = ExtractValueTypeFromExpressionFunc(operatorMember, parameterIndex: 1);
            if (valueType is not null)
            {
                valueClrType = ProfileLambdaQualifier.FormatType(valueType);
                isArrayValue = valueType is IArrayTypeSymbol;
            }
        }

        // The lambda body is rendered with type identifiers fully qualified using the
        // semantic model: <c>DateTime.UtcNow.AddDays(-days)</c> becomes
        // <c>global::System.DateTime.UtcNow.AddDays(-days)</c> so the body resolves regardless
        // of which usings the consumer file does or doesn't carry. When no compilation is
        // available (e.g., test paths that build a ResolvedProfile directly), we fall back to
        // the raw source — the resulting code may not compile if the user wrote unqualified
        // identifiers, but that's a soft regression on the test path only.
        var lambdaBodySource = ProfileLambdaQualifier.QualifyLambdaBody(lambdaSyntax.Body, compilation);

        return new CustomOperatorModel(
            OperatorName: operatorName,
            DeclaringProfileFullName: declaringProfileFullName,
            ColumnParameterName: columnParameterName,
            ValueParameterName: valueParameterName,
            ValueClrType: valueClrType,
            IsArrayValue: isArrayValue,
            LambdaBodyCSharp: lambdaBodySource,
            Location: LocationInfo.FromLocation(operatorMember.Locations.FirstOrDefault()));
    }


    private static ParenthesizedLambdaExpressionSyntax? TryFindLambdaSyntax(ISymbol operatorMember)
    {
        foreach (var syntaxReference in operatorMember.DeclaringSyntaxReferences)
        {
            var syntax = syntaxReference.GetSyntax();
            // Expression-bodied property/method: `=> <expression>` where <expression> is
            // expected to be the parenthesized lambda.
            ArrowExpressionClauseSyntax? arrow = syntax switch
            {
                PropertyDeclarationSyntax property => property.ExpressionBody,
                MethodDeclarationSyntax method => method.ExpressionBody,
                _ => null,
            };
            if (arrow is not null && arrow.Expression is ParenthesizedLambdaExpressionSyntax arrowLambda)
            {
                return arrowLambda;
            }

            // Block-bodied property getter: look for `return (a, b) => …;` inside the getter.
            if (syntax is PropertyDeclarationSyntax blockProperty && blockProperty.AccessorList is not null)
            {
                foreach (var accessor in blockProperty.AccessorList.Accessors)
                {
                    if (!accessor.IsKind(SyntaxKind.GetAccessorDeclaration)) continue;
                    if (accessor.ExpressionBody?.Expression is ParenthesizedLambdaExpressionSyntax accessorArrowLambda)
                    {
                        return accessorArrowLambda;
                    }
                    if (accessor.Body is null) continue;
                    foreach (var statement in accessor.Body.Statements)
                    {
                        if (statement is ReturnStatementSyntax returnStatement
                            && returnStatement.Expression is ParenthesizedLambdaExpressionSyntax returnLambda)
                        {
                            return returnLambda;
                        }
                    }
                }
            }

            // Block-bodied method: scan top-level return statements for a parenthesized lambda.
            if (syntax is MethodDeclarationSyntax blockMethod && blockMethod.Body is not null)
            {
                foreach (var statement in blockMethod.Body.Statements)
                {
                    if (statement is ReturnStatementSyntax returnStatement
                        && returnStatement.Expression is ParenthesizedLambdaExpressionSyntax methodReturnLambda)
                    {
                        return methodReturnLambda;
                    }
                }
            }
        }
        return null;
    }

    /// <summary>
    /// Pulls the type at <paramref name="parameterIndex"/> from a member whose return / property
    /// type is <c>Expression&lt;Func&lt;…&gt;&gt;</c>. Returns null if the member's type doesn't
    /// match that shape (defensive — analyzer FN0011 enforces the right shape upstream).
    /// </summary>
    private static ITypeSymbol? ExtractValueTypeFromExpressionFunc(ISymbol operatorMember, int parameterIndex)
    {
        ITypeSymbol? memberType = operatorMember switch
        {
            IPropertySymbol property => property.Type,
            IMethodSymbol method => method.ReturnType,
            _ => null,
        };
        if (memberType is not INamedTypeSymbol expressionType) return null;
        if (expressionType.TypeArguments.Length != 1) return null;
        if (expressionType.TypeArguments[0] is not INamedTypeSymbol funcType) return null;
        // Func<T1, …, TResult>: TypeArguments end in TResult. The column is index 0, value is 1.
        if (parameterIndex >= funcType.TypeArguments.Length - 1) return null;
        return funcType.TypeArguments[parameterIndex];
    }

    /// <summary>Checks whether the resolved profile is compatible with the property's CLR type.</summary>
    public static bool IsCompatible(ITypeSymbol clrType, string profileFullName)
    {
        var unwrapped = UnwrapNullable(clrType);
        return profileFullName switch
        {
            StringFilterFullName => unwrapped.SpecialType == SpecialType.System_String,
            BoolFilterFullName => unwrapped.SpecialType == SpecialType.System_Boolean,
            GuidFilterFullName => unwrapped.ToDisplayString() == "System.Guid",
            Int32FilterFullName => unwrapped.SpecialType == SpecialType.System_Int32,
            Int64FilterFullName => unwrapped.SpecialType == SpecialType.System_Int64,
            Int16FilterFullName => unwrapped.SpecialType == SpecialType.System_Int16,
            ByteFilterFullName => unwrapped.SpecialType == SpecialType.System_Byte,
            DecimalFilterFullName => unwrapped.SpecialType == SpecialType.System_Decimal,
            DoubleFilterFullName => unwrapped.SpecialType == SpecialType.System_Double,
            SingleFilterFullName => unwrapped.SpecialType == SpecialType.System_Single,
            DateTimeFilterFullName => unwrapped.ToDisplayString() == "System.DateTime",
            DateTimeOffsetFilterFullName => unwrapped.ToDisplayString() == "System.DateTimeOffset",
            DateOnlyFilterFullName => unwrapped.ToDisplayString() == "System.DateOnly",
            TimeOnlyFilterFullName => unwrapped.ToDisplayString() == "System.TimeOnly",
            _ => true,// Custom profiles: leave compatibility validation to the user.
        };
    }

    private static ITypeSymbol UnwrapNullable(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType
            && namedType.IsGenericType
            && namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T)
        {
            return namedType.TypeArguments[0];
        }
        return type;
    }

    /// <summary>The four operators every auto-emitted enum profile carries
    /// (<see cref="EnumProfileEmitter"/>): <c>eq</c>, <c>ne</c>, <c>in</c>, <c>isNull</c>.
    /// Used by <see cref="TryBuildVirtualEnumProfile"/> to synthesise a <see cref="ResolvedProfile"/>
    /// for an auto-emitted profile that the source compilation can't yet see.</summary>
    private static readonly string[] BuiltInEnumOperators =
        ["eq", "ne", "in", "isNull"];

    /// <summary>Index-based resolution. Returns the candidate profile full names for a property's
    /// CLR type via <see cref="ProfileIndex"/>. The caller decides what to do with 0, 1, or 2+ matches:
    /// 0 → fall back to <see cref="InferFromClrType"/> or emit FN0009 NoInferableProfile;
    /// 1 → use it; 2+ → emit FN0015 AmbiguousProfile or honour an explicit <c>[Map(typeof(X))]</c>.</summary>
    public static ResolvedProfileCandidates ResolveCandidates(ITypeSymbol clrType, ProfileIndex index)
    {
        var unwrapped = UnwrapNullable(clrType);
        var candidates = index.Lookup(unwrapped.ToDisplayString());
        return new ResolvedProfileCandidates(candidates);
    }

    /// <summary>The profile full names that match a property's CLR type via index lookup.</summary>
    public readonly struct ResolvedProfileCandidates(IReadOnlyList<string> profileFullNames)
    {
        public IReadOnlyList<string> ProfileFullNames { get; } = profileFullNames;

        public int Count => ProfileFullNames.Count;
    }
}
