//HintName: Sample.UserFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable
#pragma warning disable CS0472, CS8073
using System.Linq;
namespace Sample
{
    partial class UserFilter : global::Filtering.Net.IFilterDefinition<global::Sample.User>
    {
        /// <summary>Default page size resolved from [PageSettings] / [FilterDefaults].</summary>
        private const int _defaultPageSize = 50;
        /// <summary>Maximum page size resolved from [PageSettings] / [FilterDefaults].</summary>
        private const int _maxPageSize = 200;
        // ----- Implementation parts for [Map]-decorated configuration partials -----
        private static partial void MapDeptName() { /* configuration-only marker */ }

        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::Filtering.Net.FilterNode? where)
        {
            if (where is null) return global::Filtering.Net.FilterValidationResult.Success;
            var validationErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            ValidateNode(where, "where", validationErrors);
            return validationErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(validationErrors);
        }

        /// <summary>Recursively validates a filter expression tree, appending errors as it descends.</summary>
        private static void ValidateNode(global::Filtering.Net.FilterNode node, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors)
        {
            if (node is global::Filtering.Net.FilterGroup group)
            {
                if (group.Children.Count == 0)
                {
                    errors.Add(new global::Filtering.Net.FilterValidationError(path, global::Filtering.Net.FilterValidationCode.GroupEmpty, "Group has no children."));
                    return;
                }
                var combinatorSegment = group.Op switch
                {
                    global::Filtering.Net.LogicalOp.And => "and",
                    global::Filtering.Net.LogicalOp.Or => "or",
                    global::Filtering.Net.LogicalOp.Not => "not",
                    _ => "unknown"
                };
                for (var childIndex = 0; childIndex < group.Children.Count; childIndex++)
                {
                    var childPath = $"{path}.{combinatorSegment}[{childIndex}]";
                    ValidateNode(group.Children[childIndex], childPath, errors);
                }
                return;
            }
            if (node is global::Filtering.Net.FilterLeaf leaf)
            {
                ValidateLeaf(leaf, path, errors);
                return;
            }
            errors.Add(new global::Filtering.Net.FilterValidationError(path, global::Filtering.Net.FilterValidationCode.InvalidValueType, "Unknown FilterNode subtype."));
        }

        /// <summary>Field-name dispatcher for leaf validation. Routes to a per-property nested-class validator after uppercasing the field.</summary>
        private static void ValidateLeaf(global::Filtering.Net.FilterLeaf leaf, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors)
        {
            var fieldKey = leaf.Field.ToUpperInvariant();
            switch (fieldKey)
            {
                case "DEPARTMENT.NAME":
                case "DEPT":
                    Department_Name.Validate(leaf, path, errors);
                    break;
                default:
                    errors.Add(new global::Filtering.Net.FilterValidationError(
                        path,
                        global::Filtering.Net.FilterValidationCode.UnknownField,
                        $"Field '{leaf.Field}' is not configured for filtering.",
                        Field: leaf.Field));
                    break;
            }
        }


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::System.Collections.Generic.IReadOnlyList<global::Filtering.Net.SortItem>? sortItems)
        {
            if (sortItems is null || sortItems.Count == 0) return global::Filtering.Net.FilterValidationResult.Success;
            var validationErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            for (var sortIndex = 0; sortIndex < sortItems.Count; sortIndex++)
            {
                var sortItem = sortItems[sortIndex];
                var path = $"sort[{sortIndex}].field";
                var fieldKey = sortItem.Field.ToUpperInvariant();
                switch (fieldKey)
                {
                    default:
                        validationErrors.Add(new global::Filtering.Net.FilterValidationError(
                            path,
                            global::Filtering.Net.FilterValidationCode.NotSortable,
                            $"Field '{sortItem.Field}' is not configured as sortable.",
                            Field: sortItem.Field));
                        break;
                }
            }
            return validationErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(validationErrors);
        }


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(int? page, int? pageSize)
            => global::Filtering.Net.PageValidation.Validate(page, pageSize, _maxPageSize);


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::Filtering.Net.FilterRequest request)
        {
            if (request is null) throw new global::System.ArgumentNullException(nameof(request));
            var aggregatedErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            if (request.Where is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Where).Errors);
            }
            if (request.Sort is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Sort).Errors);
            }
            if (request.Page is not null || request.PageSize is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Page, request.PageSize).Errors);
            }
            return aggregatedErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(aggregatedErrors);
        }

        /// <inheritdoc />
        public global::System.Linq.IQueryable<global::Sample.User> ApplyFilter(global::System.Linq.IQueryable<global::Sample.User> query, global::Filtering.Net.FilterNode? where)
        {
            if (where is null) return query;
            var predicate = BuildPredicate(where);
            return query.Where(predicate);
        }

        /// <summary>Recursive subtype dispatcher: groups → CombineGroup, leaves → BuildLeaf.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> BuildPredicate(global::Filtering.Net.FilterNode node)
        {
            if (node is global::Filtering.Net.FilterGroup group) return CombineGroup(group);
            if (node is global::Filtering.Net.FilterLeaf leaf) return BuildLeaf(leaf);
            throw new global::Filtering.Net.FilterDispatchException("Unknown FilterNode subtype.");
        }

        /// <summary>Reduces a FilterGroup's children into a single predicate via PredicateBuilder.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> CombineGroup(global::Filtering.Net.FilterGroup group)
        {
            if (group.Children.Count == 0) throw new global::Filtering.Net.FilterDispatchException("Group has no children (validation should have caught this).");
            if (group.Op == global::Filtering.Net.LogicalOp.Not)
            {
                if (group.Children.Count != 1) throw new global::Filtering.Net.FilterDispatchException("Not group requires exactly one child.");
                var negatedChild = BuildPredicate(group.Children[0]);
                return global::Filtering.Net.PredicateBuilder.Not(negatedChild);
            }
            var combinedPredicate = BuildPredicate(group.Children[0]);
            for (var childIndex = 1; childIndex < group.Children.Count; childIndex++)
            {
                var nextPredicate = BuildPredicate(group.Children[childIndex]);
                combinedPredicate = group.Op switch
                {
                    global::Filtering.Net.LogicalOp.And => global::Filtering.Net.PredicateBuilder.AndAlso(combinedPredicate, nextPredicate),
                    global::Filtering.Net.LogicalOp.Or => global::Filtering.Net.PredicateBuilder.OrElse(combinedPredicate, nextPredicate),
                    _ => throw new global::Filtering.Net.FilterDispatchException($"Unknown LogicalOp '{group.Op}'.")
                };
            }
            return combinedPredicate;
        }

        /// <summary>Field-key dispatcher for leaves; routes to a per-property nested-class Build method.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> BuildLeaf(global::Filtering.Net.FilterLeaf leaf)
        {
            var fieldKey = leaf.Field.ToUpperInvariant();
            switch (fieldKey)
            {
                case "DEPARTMENT.NAME":
                case "DEPT":
                    return Department_Name.Build(leaf);
                default:
                    throw new global::Filtering.Net.FilterDispatchException($"Unknown field '{leaf.Field}' (validation should have caught this).");
            }
        }


        /// <inheritdoc />
        public global::System.Linq.IQueryable<global::Sample.User> ApplySorting(global::System.Linq.IQueryable<global::Sample.User> query, global::System.Collections.Generic.IReadOnlyList<global::Filtering.Net.SortItem>? sortItems, int? page = null, int? pageSize = null)
        {
            global::System.Linq.IQueryable<global::Sample.User> resultQuery = query;
            if (sortItems is { Count: > 0 })
            {
                var firstSort = sortItems[0];
                throw new global::Filtering.Net.FilterDispatchException($"No sortable fields are configured (got '{firstSort.Field}').");
            }
            if (page is not null || pageSize is not null)
            {
                var pageNumber = global::System.Math.Max(1, page ?? 1);
                var resolvedPageSize = global::System.Math.Min(global::System.Math.Max(1, pageSize ?? _defaultPageSize), _maxPageSize);
                resultQuery = resultQuery.Skip((pageNumber - 1) * resolvedPageSize).Take(resolvedPageSize);
            }
            return resultQuery;
        }

    }

    /// <summary>Per-property helpers for 'Department.Name'.</summary>
    file static class Department_Name
    {
        /// <summary>Builds the typed predicate for a leaf targeting property 'Department.Name'.</summary>
        public static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> Build(global::Filtering.Net.FilterLeaf leaf)
        {
            var operatorKey = leaf.Operator.ToUpperInvariant();
            switch (operatorKey)
            {
                case "EQ":
                case "NE":
                case "CONTAINS":
                case "STARTSWITH":
                case "ENDSWITH":
                    {
                        if (!global::Filtering.Net.StringFilter.TryGetValue(leaf.Value, out var rawLeafValue, out var typeError))
                            throw new global::Filtering.Net.FilterDispatchException($"Apply-time value extraction failed: {typeError}");
                        var typedLeafValue = rawLeafValue;
                        return operatorKey switch
                        {
                            "EQ" => Eq(typedLeafValue),
                            "NE" => Ne(typedLeafValue),
                            "CONTAINS" => Contains(typedLeafValue),
                            "STARTSWITH" => StartsWith(typedLeafValue),
                            "ENDSWITH" => EndsWith(typedLeafValue),
                            _ => throw new global::Filtering.Net.FilterDispatchException($"Unreachable operator '{operatorKey}' for property 'Department.Name'.")
                        };
                    }
                case "IN":
                    {
                        if (!global::Filtering.Net.StringFilter.TryGetArray(leaf.Value, out var typedLeafValues, out var arrayError))
                            throw new global::Filtering.Net.FilterDispatchException($"Apply-time array extraction failed: {arrayError}");
                        return In(typedLeafValues);
                    }
                case "ISNULL":
                    return IsNull();
                default:
                    throw new global::Filtering.Net.FilterDispatchException($"Unknown operator '{leaf.Operator}' for 'Department.Name' (validation should have caught this).");
            }
        }

        private static readonly string[] _allowedScalarOps = new[] { "EQ", "NE", "CONTAINS", "STARTSWITH", "ENDSWITH" };
        private static readonly string[] _allowedArrayOps = new[] { "IN" };
        private static readonly string[] _allowedNoneOps = new[] { "ISNULL" };

        /// <summary>Validates a leaf whose field resolves to property 'Department.Name'.</summary>
        public static void Validate(global::Filtering.Net.FilterLeaf leaf, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors) =>
            global::Filtering.Net.LeafValidation.ValidateMappedLeaf<string>(
                leaf,
                path,
                errors,
                "Department.Name",
                _allowedScalarOps,
                _allowedArrayOps,
                _allowedNoneOps,
                global::Filtering.Net.StringFilter.TryGetValue,
                global::Filtering.Net.StringFilter.TryGetArray);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> Eq(string leafValue) => entity => entity.Department.Name == leafValue;
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> Ne(string leafValue) => entity => entity.Department.Name != leafValue;
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> Contains(string leafValue) => entity => entity.Department.Name.Contains(leafValue);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> StartsWith(string leafValue) => entity => entity.Department.Name.StartsWith(leafValue);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> EndsWith(string leafValue) => entity => entity.Department.Name.EndsWith(leafValue);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> In(string[] leafValues) => entity => leafValues.Contains(entity.Department.Name);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> IsNull() => entity => entity.Department.Name == null;
    }

}
