//HintName: FilteringProfiles.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations

namespace Filtering.Net.Generated
{
    /// <summary>Runtime form of the <c>Sample.RecencyFilter</c> profile.</summary>
    internal static class Sample_RecencyFilterProfile
    {
        public static readonly global::Filtering.Net.FilterProfile<global::System.DateTime> Instance =
            global::Filtering.Net.DateTimeFilter.Profile.ExtendWithOverrides("RecencyFilter",
                global::Filtering.Net.FilterOperator.Value<global::System.DateTime, int>("withinDays", global::Sample.RecencyFilter.WithinDays));
    }
}
