//HintName: FilteringServiceCollectionExtensions.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable

namespace Filtering.Net
{
    /// <summary>DI registrations for all <see cref="IFilterDefinition{TEntity}"/> implementations discovered by Filtering.Net.Generator in this assembly.</summary>
    public static class FilteringServiceCollectionExtensions
    {
        /// <summary>Registers every generated filter class as a singleton implementation of <see cref="IFilterDefinition{TEntity}"/>. Filters use the parameterless constructor, falling back to <see cref="global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver"/> for typed-value deserialization. No AOT support; for AOT-clean trim-safe deserialization use the <c>IJsonTypeInfoResolver</c> overload.</summary>
        /// <param name="services">The service collection to extend.</param>
        /// <returns>The same collection for chaining.</returns>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddFiltering(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.User>, global::Sample.UserFilter>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.Order>, global::Sample.OrderFilter>(services);
            return services;
        }

        /// <summary>Registers every generated filter class as a singleton, constructed with the supplied <see cref="global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver"/>. Use this overload to wire a <c>JsonSerializerContext</c> into typed-value deserialization for trim-safe / AOT scenarios.</summary>
        /// <param name="services">The service collection to extend.</param>
        /// <param name="typeInfoResolver">Resolver chain — typically a single <c>JsonSerializerContext</c> or <c>JsonTypeInfoResolver.Combine(...)</c>.</param>
        /// <returns>The same collection for chaining.</returns>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddFiltering(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
        {
            if (typeInfoResolver is null) throw new global::System.ArgumentNullException(nameof(typeInfoResolver));
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.User>, global::Sample.UserFilter>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.Order>, global::Sample.OrderFilter>(services);
            return services;
        }

        /// <summary>Registers every generated filter class as a singleton constructed via a factory that receives the <see cref="global::System.IServiceProvider"/>. Use this overload to compose a resolver chain from DI-resolved services.</summary>
        /// <param name="services">The service collection to extend.</param>
        /// <param name="resolverFactory">Factory invoked at filter-construction time.</param>
        /// <returns>The same collection for chaining.</returns>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddFiltering(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Func<global::System.IServiceProvider, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver> resolverFactory)
        {
            if (resolverFactory is null) throw new global::System.ArgumentNullException(nameof(resolverFactory));
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.User>, global::Sample.UserFilter>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Filtering.Net.IFilterDefinition<global::Sample.Order>, global::Sample.OrderFilter>(services);
            return services;
        }
    }
}
