//HintName: TestNs.CompanyFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace TestNs
{
    partial class CompanyFilter : global::Filtering.Net.FilterDefinition<global::TestNs.Company>
    {
        /// <summary>Initializes a new instance.</summary>
        public CompanyFilter()
            : base(CreateSchema(serializerOptions: null, global::Filtering.Net.FilterNestingContext.Root)) { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::TestNs.Company> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions, global::Filtering.Net.FilterNestingContext nestingContext) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::TestNs.Company>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .Add(global::Filtering.Net.FilterProperty.Map("Name", (global::TestNs.Company entity) => entity.Name, global::Filtering.Net.StringFilter.Profile)
                    .Build())
                .Build();
    }
}
