//HintName: TestNs.UserFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace TestNs
{
    partial class UserFilter : global::Filtering.Net.FilterDefinition<global::TestNs.User>
    {
        /// <summary>Initializes a new instance.</summary>
        public UserFilter()
            : base(CreateSchema(serializerOptions: null, global::Filtering.Net.FilterNestingContext.Root)) { }

        private static partial void MapDept() { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::TestNs.User> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions, global::Filtering.Net.FilterNestingContext nestingContext) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::TestNs.User>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .AddNested(nestingContext, "TestNs.UserFilter.MapDept", maxDepth: 0,
                    nestedContext => global::TestNs.DepartmentFilter.CreateSchema(serializerOptions, nestedContext),
                    (global::TestNs.User entity) => entity.Department, "Department", only: new string[] { "Id" }, except: null, disableSorting: false)
                .Build();
    }
}
