//HintName: TestNs.UserFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace TestNs
{
    partial class UserFilter : global::Filtering.Net.FilterDefinition<global::TestNs.User>
    {
        /// <summary>Initializes a new instance using a reflection-based <see cref="global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver"/>.</summary>
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Uses DefaultJsonTypeInfoResolver which is not trim-safe. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Uses DefaultJsonTypeInfoResolver which requires dynamic code. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        public UserFilter()
            : this(new global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()) { }

        /// <summary>Initializes a new instance with a caller-supplied <see cref="global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver"/> for typed operator values.</summary>
        /// <param name="typeInfoResolver">The resolver chain (typically a <c>JsonSerializerContext</c> or <c>JsonTypeInfoResolver.Combine(...)</c>).</param>
        public UserFilter(global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
            : base(CreateSchema(CreateSerializerOptions(typeInfoResolver))) { }

        private static global::System.Text.Json.JsonSerializerOptions CreateSerializerOptions(global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
        {
            if (typeInfoResolver is null) throw new global::System.ArgumentNullException(nameof(typeInfoResolver));
            return new global::System.Text.Json.JsonSerializerOptions { TypeInfoResolver = typeInfoResolver };
        }

        private static partial void MapDept() { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::TestNs.User> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::TestNs.User>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .AddRange(global::TestNs.DepartmentFilter.CreateSchema(serializerOptions)
                    .LiftInto<global::TestNs.User>(entity => entity.Department, "Department", only: null, except: null, disableSorting: false))
                .Build();
    }
}
