//HintName: Sample.UserFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable
#pragma warning disable CS0472, CS8073
using System.Linq;
namespace Sample
{
    partial class UserFilter : global::Filtering.Net.IFilterDefinition<global::Sample.User>
    {
        /// <summary>Default page size resolved from [PageSettings] / [FilterDefaults].</summary>
        private const int _defaultPageSize = 50;
        /// <summary>Maximum page size resolved from [PageSettings] / [FilterDefaults].</summary>
        private const int _maxPageSize = 200;
        /// <summary>JSON serializer options used by typed-value deserialization. Initialized in the constructor; routed to <c>JsonSerializer.Deserialize</c> via the resolver chain.</summary>
        private readonly global::System.Text.Json.JsonSerializerOptions _serializerOptions;

        /// <summary>Initializes a new instance using a reflection-based <see cref="global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver"/>.</summary>
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Uses DefaultJsonTypeInfoResolver which is not trim-safe. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Uses DefaultJsonTypeInfoResolver which requires dynamic code. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        public UserFilter()
            : this(new global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()) { }

        /// <summary>Initializes a new instance with a caller-supplied <see cref="global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver"/>.</summary>
        /// <param name="typeInfoResolver">The resolver chain (typically a <c>JsonSerializerContext</c> or <c>JsonTypeInfoResolver.Combine(...)</c>).</param>
        public UserFilter(global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
        {
            if (typeInfoResolver is null) throw new global::System.ArgumentNullException(nameof(typeInfoResolver));
            _serializerOptions = new global::System.Text.Json.JsonSerializerOptions { TypeInfoResolver = typeInfoResolver };
        }

        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::Filtering.Net.FilterNode? where)
        {
            if (where is null) return global::Filtering.Net.FilterValidationResult.Success;
            var validationErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            ValidateNode(where, "where", validationErrors, _serializerOptions);
            return validationErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(validationErrors);
        }

        /// <summary>Recursively validates a filter expression tree, appending errors as it descends.</summary>
        private static void ValidateNode(global::Filtering.Net.FilterNode node, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (node is global::Filtering.Net.FilterGroup group)
            {
                if (group.Children.Count == 0)
                {
                    errors.Add(new global::Filtering.Net.FilterValidationError(path, global::Filtering.Net.FilterValidationCode.GroupEmpty, "Group has no children."));
                    return;
                }
                var combinatorSegment = group.Op switch
                {
                    global::Filtering.Net.LogicalOp.And => "and",
                    global::Filtering.Net.LogicalOp.Or => "or",
                    global::Filtering.Net.LogicalOp.Not => "not",
                    _ => "unknown"
                };
                for (var childIndex = 0; childIndex < group.Children.Count; childIndex++)
                {
                    var childPath = $"{path}.{combinatorSegment}[{childIndex}]";
                    ValidateNode(group.Children[childIndex], childPath, errors, options);
                }
                return;
            }
            if (node is global::Filtering.Net.FilterLeaf leaf)
            {
                ValidateLeaf(leaf, path, errors, options);
                return;
            }
            errors.Add(new global::Filtering.Net.FilterValidationError(path, global::Filtering.Net.FilterValidationCode.InvalidValueType, "Unknown FilterNode subtype."));
        }

        /// <summary>Field-name dispatcher for leaf validation. Routes to a per-property nested-class validator after uppercasing the field.</summary>
        private static void ValidateLeaf(global::Filtering.Net.FilterLeaf leaf, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors, global::System.Text.Json.JsonSerializerOptions options)
        {
            var fieldKey = leaf.Field.ToUpperInvariant();
            switch (fieldKey)
            {
                case "TAGS":
                    Tags.Validate(leaf, path, errors, options);
                    break;
                default:
                    errors.Add(new global::Filtering.Net.FilterValidationError(
                        path,
                        global::Filtering.Net.FilterValidationCode.UnknownField,
                        $"Field '{leaf.Field}' is not configured for filtering.",
                        Field: leaf.Field));
                    break;
            }
        }


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::System.Collections.Generic.IReadOnlyList<global::Filtering.Net.SortItem>? sortItems)
        {
            if (sortItems is null || sortItems.Count == 0) return global::Filtering.Net.FilterValidationResult.Success;
            var validationErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            for (var sortIndex = 0; sortIndex < sortItems.Count; sortIndex++)
            {
                var sortItem = sortItems[sortIndex];
                var path = $"sort[{sortIndex}].field";
                var fieldKey = sortItem.Field.ToUpperInvariant();
                switch (fieldKey)
                {
                    default:
                        validationErrors.Add(new global::Filtering.Net.FilterValidationError(
                            path,
                            global::Filtering.Net.FilterValidationCode.NotSortable,
                            $"Field '{sortItem.Field}' is not configured as sortable.",
                            Field: sortItem.Field));
                        break;
                }
            }
            return validationErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(validationErrors);
        }


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(int? page, int? pageSize)
            => global::Filtering.Net.PageValidation.Validate(page, pageSize, _maxPageSize);


        /// <inheritdoc />
        public global::Filtering.Net.FilterValidationResult Validate(global::Filtering.Net.FilterRequest request)
        {
            if (request is null) throw new global::System.ArgumentNullException(nameof(request));
            var aggregatedErrors = new global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError>();
            if (request.Where is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Where).Errors);
            }
            if (request.Sort is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Sort).Errors);
            }
            if (request.Page is not null || request.PageSize is not null)
            {
                aggregatedErrors.AddRange(Validate(request.Page, request.PageSize).Errors);
            }
            return aggregatedErrors.Count == 0
                ? global::Filtering.Net.FilterValidationResult.Success
                : new global::Filtering.Net.FilterValidationResult(aggregatedErrors);
        }

        /// <inheritdoc />
        public global::System.Linq.IQueryable<global::Sample.User> ApplyFilter(global::System.Linq.IQueryable<global::Sample.User> query, global::Filtering.Net.FilterNode? where)
        {
            if (where is null) return query;
            var predicate = BuildPredicate(where, _serializerOptions);
            return query.Where(predicate);
        }

        /// <summary>Recursive subtype dispatcher: groups → CombineGroup, leaves → BuildLeaf.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> BuildPredicate(global::Filtering.Net.FilterNode node, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (node is global::Filtering.Net.FilterGroup group) return CombineGroup(group, options);
            if (node is global::Filtering.Net.FilterLeaf leaf) return BuildLeaf(leaf, options);
            throw new global::Filtering.Net.FilterDispatchException("Unknown FilterNode subtype.");
        }

        /// <summary>Reduces a FilterGroup's children into a single predicate via PredicateBuilder.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> CombineGroup(global::Filtering.Net.FilterGroup group, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (group.Children.Count == 0) throw new global::Filtering.Net.FilterDispatchException("Group has no children (validation should have caught this).");
            if (group.Op == global::Filtering.Net.LogicalOp.Not)
            {
                if (group.Children.Count != 1) throw new global::Filtering.Net.FilterDispatchException("Not group requires exactly one child.");
                var negatedChild = BuildPredicate(group.Children[0], options);
                return global::Filtering.Net.PredicateBuilder.Not(negatedChild);
            }
            var combinedPredicate = BuildPredicate(group.Children[0], options);
            for (var childIndex = 1; childIndex < group.Children.Count; childIndex++)
            {
                var nextPredicate = BuildPredicate(group.Children[childIndex], options);
                combinedPredicate = group.Op switch
                {
                    global::Filtering.Net.LogicalOp.And => global::Filtering.Net.PredicateBuilder.AndAlso(combinedPredicate, nextPredicate),
                    global::Filtering.Net.LogicalOp.Or => global::Filtering.Net.PredicateBuilder.OrElse(combinedPredicate, nextPredicate),
                    _ => throw new global::Filtering.Net.FilterDispatchException($"Unknown LogicalOp '{group.Op}'.")
                };
            }
            return combinedPredicate;
        }

        /// <summary>Field-key dispatcher for leaves; routes to a per-property nested-class Build method.</summary>
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> BuildLeaf(global::Filtering.Net.FilterLeaf leaf, global::System.Text.Json.JsonSerializerOptions options)
        {
            var fieldKey = leaf.Field.ToUpperInvariant();
            switch (fieldKey)
            {
                case "TAGS":
                    return Tags.Build(leaf, options);
                default:
                    throw new global::Filtering.Net.FilterDispatchException($"Unknown field '{leaf.Field}' (validation should have caught this).");
            }
        }


        /// <inheritdoc />
        public global::System.Linq.IQueryable<global::Sample.User> ApplySorting(global::System.Linq.IQueryable<global::Sample.User> query, global::System.Collections.Generic.IReadOnlyList<global::Filtering.Net.SortItem>? sortItems, int? page = null, int? pageSize = null)
        {
            global::System.Linq.IQueryable<global::Sample.User> resultQuery = query;
            if (sortItems is { Count: > 0 })
            {
                var firstSort = sortItems[0];
                throw new global::Filtering.Net.FilterDispatchException($"No sortable fields are configured (got '{firstSort.Field}').");
            }
            if (page is not null || pageSize is not null)
            {
                var pageNumber = global::System.Math.Max(1, page ?? 1);
                var resolvedPageSize = global::System.Math.Min(global::System.Math.Max(1, pageSize ?? _defaultPageSize), _maxPageSize);
                resultQuery = resultQuery.Skip((pageNumber - 1) * resolvedPageSize).Take(resolvedPageSize);
            }
            return resultQuery;
        }

    }

    /// <summary>Per-property helpers for [PropertyMap]-overridden property 'Tags'.</summary>
    file static class Tags
    {
        /// <summary>Builds the typed predicate for a leaf targeting [PropertyMap]-overridden property 'Tags'.</summary>
        public static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> Build(global::Filtering.Net.FilterLeaf leaf, global::System.Text.Json.JsonSerializerOptions options)
        {
            var operatorKey = leaf.Operator.ToUpperInvariant();
            switch (operatorKey)
            {
                case "ANYEQ":
                    {
                        try
                        {
                            var typeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string));
                            var typedLeafValue = global::System.Text.Json.JsonSerializer.Deserialize(leaf.Value.GetRawText(), typeInfo)!;
                            return AnyEq(typedLeafValue);
                        }
                        catch (global::System.Exception extractionError)
                            when (extractionError is global::System.Text.Json.JsonException
                               || extractionError is global::System.NotSupportedException
                               || extractionError is global::System.InvalidOperationException
                               || extractionError is global::System.InvalidCastException)
                        {
                            throw new global::Filtering.Net.FilterDispatchException(
                                $"Apply-time value extraction failed for [PropertyMap] override 'anyEq': {extractionError.Message}",
                                extractionError);
                        }
                    }
                case "ANYCONTAINS":
                    {
                        try
                        {
                            var typeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string));
                            var typedLeafValue = global::System.Text.Json.JsonSerializer.Deserialize(leaf.Value.GetRawText(), typeInfo)!;
                            return AnyContains(typedLeafValue);
                        }
                        catch (global::System.Exception extractionError)
                            when (extractionError is global::System.Text.Json.JsonException
                               || extractionError is global::System.NotSupportedException
                               || extractionError is global::System.InvalidOperationException
                               || extractionError is global::System.InvalidCastException)
                        {
                            throw new global::Filtering.Net.FilterDispatchException(
                                $"Apply-time value extraction failed for [PropertyMap] override 'anyContains': {extractionError.Message}",
                                extractionError);
                        }
                    }
                default:
                    throw new global::Filtering.Net.FilterDispatchException($"Unknown operator '{leaf.Operator}' for 'Tags' (validation should have caught this).");
            }
        }

        /// <summary>Validates a leaf whose field resolves to [PropertyMap]-overridden property 'Tags'.</summary>
        public static void Validate(global::Filtering.Net.FilterLeaf leaf, string path, global::System.Collections.Generic.List<global::Filtering.Net.FilterValidationError> errors, global::System.Text.Json.JsonSerializerOptions options)
        {
            switch (leaf.Operator.ToUpperInvariant())
            {
                case "ANYEQ":
                    try
                    {
                        var typeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string));
                        _ = global::System.Text.Json.JsonSerializer.Deserialize(leaf.Value.GetRawText(), typeInfo);
                    }
                    catch (global::System.Exception extractionError)
                        when (extractionError is global::System.Text.Json.JsonException
                           || extractionError is global::System.NotSupportedException
                           || extractionError is global::System.InvalidOperationException
                           || extractionError is global::System.InvalidCastException)
                    {
                        global::Filtering.Net.LeafValidation.AddTypeError(errors, leaf, path, extractionError.Message);
                    }
                    break;
                case "ANYCONTAINS":
                    try
                    {
                        var typeInfo = (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)options.GetTypeInfo(typeof(string));
                        _ = global::System.Text.Json.JsonSerializer.Deserialize(leaf.Value.GetRawText(), typeInfo);
                    }
                    catch (global::System.Exception extractionError)
                        when (extractionError is global::System.Text.Json.JsonException
                           || extractionError is global::System.NotSupportedException
                           || extractionError is global::System.InvalidOperationException
                           || extractionError is global::System.InvalidCastException)
                    {
                        global::Filtering.Net.LeafValidation.AddTypeError(errors, leaf, path, extractionError.Message);
                    }
                    break;
                default:
                    global::Filtering.Net.LeafValidation.AddOperatorError(errors, leaf, path, "Tags");
                    break;
            }
        }
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> AnyEq(string leafValue) => entity => entity.Tags.Any(tag => tag == leafValue);
        private static global::System.Linq.Expressions.Expression<global::System.Func<global::Sample.User, bool>> AnyContains(string leafValue) => entity => entity.Tags.Any(tag => tag.Contains(leafValue));
    }

}
