//HintName: Sample.PersonFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace Sample
{
    partial class PersonFilter : global::Filtering.Net.FilterDefinition<global::Sample.Person>
    {
        /// <summary>Initializes a new instance.</summary>
        public PersonFilter()
            : base(CreateSchema(serializerOptions: null, global::Filtering.Net.FilterNestingContext.Root)) { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::Sample.Person> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions, global::Filtering.Net.FilterNestingContext nestingContext) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::Sample.Person>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .Add(global::Filtering.Net.FilterProperty.MapRule("FullName", MapFullName(new global::Filtering.Net.FilterRuleBuilder<global::Sample.Person, string>()))
                    .Alias("name")
                    .Sortable(global::Filtering.Net.SortDir.Desc)
                    .Build())
                .Build();
    }
}
