//HintName: Sample.OrderFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace Sample
{
    partial class OrderFilter : global::Filtering.Net.FilterDefinition<global::Sample.Order>
    {
        /// <summary>Initializes a new instance.</summary>
        public OrderFilter()
            : base(CreateSchema(serializerOptions: null, global::Filtering.Net.FilterNestingContext.Root)) { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::Sample.Order> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions, global::Filtering.Net.FilterNestingContext nestingContext) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::Sample.Order>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .Add(global::Filtering.Net.FilterProperty.Map("Reference", (global::Sample.Order entity) => entity.Reference, global::Filtering.Net.StringFilter.Profile)
                    .Build())
                .Build();
    }
}
