//HintName: FilteringProfiles.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations

namespace Filtering.Net.Generated
{
    /// <summary>Runtime form of the <c>Sample.StringFilterPlus</c> profile.</summary>
    internal static class Sample_StringFilterPlusProfile
    {
        public static readonly global::Filtering.Net.FilterProfile<string> Instance =
            global::Filtering.Net.StringFilter.Profile.Extend("StringFilterPlus",
                global::Filtering.Net.FilterOperator.Value<string, string>("fuzzy", global::Sample.StringFilterPlus.Fuzzy));
    }
}
