//HintName: Sample.OrderFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace Sample
{
    partial class OrderFilter : global::Filtering.Net.FilterDefinition<global::Sample.Order>
    {
        /// <summary>Initializes a new instance using a reflection-based <see cref="global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver"/>.</summary>
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Uses DefaultJsonTypeInfoResolver which is not trim-safe. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Uses DefaultJsonTypeInfoResolver which requires dynamic code. Use the IJsonTypeInfoResolver-accepting constructor for trim/AOT scenarios.")]
        public OrderFilter()
            : this(new global::System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()) { }

        /// <summary>Initializes a new instance with a caller-supplied <see cref="global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver"/> for typed operator values.</summary>
        /// <param name="typeInfoResolver">The resolver chain (typically a <c>JsonSerializerContext</c> or <c>JsonTypeInfoResolver.Combine(...)</c>).</param>
        public OrderFilter(global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
            : base(CreateSchema(CreateSerializerOptions(typeInfoResolver))) { }

        private static global::System.Text.Json.JsonSerializerOptions CreateSerializerOptions(global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver typeInfoResolver)
        {
            if (typeInfoResolver is null) throw new global::System.ArgumentNullException(nameof(typeInfoResolver));
            return new global::System.Text.Json.JsonSerializerOptions { TypeInfoResolver = typeInfoResolver };
        }

        private static partial void MapReference() { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::Sample.Order> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::Sample.Order>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .Add(global::Filtering.Net.FilterProperty.Map("Reference", (global::Sample.Order entity) => entity.Reference, global::Filtering.Net.Generated.Sample_StringFilterPlusProfile.Instance)
                    .Only("fuzzy")
                    .Build())
                .Build();
    }
}
