//HintName: Sample.UserFilter.g.cs
// <auto-generated by Filtering.Net.Generator />
#nullable enable annotations
namespace Sample
{
    partial class UserFilter : global::Filtering.Net.FilterDefinition<global::Sample.User>
    {
        /// <summary>Initializes a new instance.</summary>
        public UserFilter()
            : base(CreateSchema(serializerOptions: null)) { }

        private static partial void MapName() { }

        /// <summary>Builds the schema of this filter: one entry per mapping declared on the class.</summary>
        internal static global::Filtering.Net.FilterSchema<global::Sample.User> CreateSchema(global::System.Text.Json.JsonSerializerOptions? serializerOptions) =>
            new global::Filtering.Net.FilterSchemaBuilder<global::Sample.User>(
                    new global::Filtering.Net.FilterSettings(50, 200, 10, 50),
                    serializerOptions)
                .Add(global::Filtering.Net.FilterProperty.Map("Name", (global::Sample.User entity) => entity.Name, global::Filtering.Net.StringFilter.Profile)
                    .Build())
                .Build();
    }
}
